version: "3.7"

services:
  go-mongodb:
    image: mongo:5.0.3-nanoserver-1809
    volumes:
      - .\mongo_data:c:\data\db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "secret"